### ISSUE TITLE
 Practica diagrama de secuencia

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-alfa-dinamita#1]
[Diagrama_de_secuencia.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-alfa-dinamita/files/7823975/Diagrama_de_secuencia.pdf)

**Comment by christopheremv** [comment]
Calificación: 29

**Comment by josealfredo79** [comment]
Solo a los mensajes en el diagrama de secuencia hace falta los parametros

**Comment by josealfredo79** [comment]
Revisado
